### ISSUE TITLE
[Windows] Expose the EpisodesTitle completely

### ISSUE THREAD

**Issue by bachig26** [miru-project/miru-app#107]
### Brief summary

At the moment, when the text length exceeds one line, the next lines are cropped maybe due to the box height being restricted to certain value.

I'm hoping to see the height being adapted the text, to expose them completely.

### Screenshot

![miru_oCGDpF2ZC1](https://github.com/miru-project/miru-app/assets/96393348/abdab57f-744d-4061-a452-89cceb533890)
![miru_aR5dfJNqVg](https://github.com/miru-project/miru-app/assets/96393348/434e46ef-30da-4dbd-99db-b9debabd1c3c)

### Steps to reproduce

based on the screenshots provided,

1. open the titles like MI Dead Reckoning Part One in `MoviesArc` and I am Nobody in `Kissasian`
2. then you see the same issue in the Episodes list.

### Miru version

1.7.1

### Device

Lenovo ideapad (Windows 10)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] If this is an issue with a extension, I should be opening an issue in the [extension repository](https://github.com/miru-project/repo/issues/new).

**Comment by OshekharO** [comment]
That will break the consistency of the ui.
