### ISSUE TITLE
Add option to use proxy and to change DNS 

### ISSUE THREAD

**Issue by Gamer750** [miru-project/miru-app#12]
To bypass restrictions

**Comment by OshekharO** [comment]
+1 priority feature

**Comment by bachig26** [comment]
@MiaoMint will it be possible to embed the vpn protocols (OpenVPN, WireGuard, IKEv2, etc.) into the app, so we can load the vpn config to use?

example (WireGuard): https://pub.dev/documentation/wireguard_vpn/latest/ | https://www.wireguard.com/embedding/#embedding-wireguard-in-custom-applications
