### ISSUE TITLE
(NSFW/18+) JavHD content crashes Miru

### ISSUE THREAD

**Issue by ClickClack7531** [miru-project/miru-app#120]
### Brief summary

 JUFE-362 from JavHD crashes Miru

### Steps to reproduce

Warning: NSFW content.
1. Install JavHD repository
2. Enable Show NSFW content
3. Search for JUFE-362
4. Open the first result from JavHD
5. Attempt to watch it
6. *Miru crashes*

### Miru version

1.7.2

### Device

S10-5G

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] If this is an issue with a extension, I should be opening an issue in the [extension repository](https://github.com/miru-project/repo/issues/new).

**Comment by OshekharO** [comment]
Fixed this in https://github.com/miru-project/repo/commit/04de3fe830fb232bc3b597845ce507f8393c8c47
