### ISSUE TITLE
poor video quality

### ISSUE THREAD

**Issue by MarshMeadow** [miru-project/miru-app#123]
### Describe your suggested feature

we need video quality options like 720p or higher 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by Zaxx69** [comment]
I am facing the same problem and some providers are not working

**Comment by OshekharO** [comment]
> I am facing the same problem and some providers are not working

Which provider are not working? Except for 9anime, AniWatch, sflix and fliqhq. Also in which extension you facing poor quality issue because in almost all extension there should be very few which have quality below 720p.

**Comment by undefined-zzk** [comment]
6

**Comment by MiaoMint** [comment]
Video quality options are now available from m3u8
