### ISSUE TITLE
Filters in the anime search

### ISSUE THREAD

**Issue by Imaguy0** [miru-project/miru-app#127]
### Describe your suggested feature

Should be nice if we can filter the anime like [romance, adventure, action,etc]

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by OshekharO** [comment]
Infact filter feature is already present, rest depends whether extension developer's are willing to give extra effort to add or not.

**Comment by Imaguy0** [comment]
Oh i see
