### ISSUE TITLE
可以加一个自定义跳进度的功能吗？

### ISSUE THREAD

**Issue by Joackk** [miru-project/miru-app#135]
### Describe your suggested feature

就是可以给视频自定义，在什么时间触发跳转，然后跳到xxx的时间进度，用来自定义跳转片头片尾

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by Joackk** [comment]
比如把设置的跳转规则跟播放的历史记录存放在一起？有播放记录就读取之前的规则，没有就默认不进行跳转

**Comment by MiaoMint** [comment]
感觉没太必要 或者 这个应该要扩展提供 而不是用户手动设置

**Comment by Joackk** [comment]
> 感觉没太必要 或者 这个应该要扩展提供 而不是用户手动设置

直接在扩展里设置吗？因为不同的视频片头片尾也不太一样，所以想如果是自己设置的话那应该会比较准一点

**Comment by MiaoMint** [comment]
我的意思是让扩展提供跳过片头片尾的支持，软件就只是提供一个接口。

**Comment by Joackk** [comment]
soga
