### ISSUE TITLE
内存占用过大

### ISSUE THREAD

**Issue by Joackk** [miru-project/miru-app#138]
### Brief summary

就正常使用，突然发现整个电脑都卡了起来，看了下任务管理器发现内存用满了，我是32G内存
![image](https://github.com/miru-project/miru-app/assets/45162558/39d04464-42aa-4126-ad9a-e4ec198a9c40)
并且关了进程还有个后台进程再继续占用超高的内存。最近偶尔会遇到。与之前对比就是最近多装了几个插件。然后搜索时候有时候会有几个报错
![image](https://github.com/miru-project/miru-app/assets/45162558/c17fd52a-6ff9-46e9-b1cc-982a7b22fa19)
不知道是不是上面这个报错导致的

### Miru version

1.7.2

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] If this is an issue with a extension, I should be opening an issue in the [extension repository](https://github.com/miru-project/repo/issues/new).

**Comment by Joackk** [comment]
在看了会视频后返回首页后，发现这内存占用在不断增加。虽然增加的不快，但是一直在加，是没有自动释放内存吗？

**Comment by Joackk** [comment]
> 按理来说应该退出视频界面会释放内存，你只是看了视频然后退出视频界面然后内存就开始一直增加吗？

我也不确定这是什么情况了，因为最近一段时间使用中，有时候打开半小时看了会视频他就开始使用了4-8G内存了，然后关闭重开又恢复正常。有的时候开一天中途也会使用看视频什么的，但是内存都使用正常。有点无法确定他这个到底是啥情况了。就正常使用有的时候用一会就内存占用飙升到几个G，有的时候用一天他也正常

**Comment by yhsj0919** [comment]
内存增加大概率是 media_kit的问题，在我应用中，多次调用 player.open(),会导致内存持续增加，而不会释放，长时间播放也会导致内存增加

**Comment by yhsj0919** [comment]
可以尝试限制一下最大缓存
```dart
void initVideo() async {
    if (player.platform is NativePlayer) {
      await (player.platform as dynamic).setProperty('cache', 'yes');
    }
    if (player.platform is NativePlayer) {
      await (player.platform as dynamic).setProperty('demuxer-max-bytes', '30MiB');
    }
    if (player.platform is NativePlayer) {
      await (player.platform as dynamic).setProperty('demuxer-readahead-secs', '20');
    }
  }
```
```demuxer-max-bytes ```  和  ```demuxer-readahead-secs ```

我测试的时候没有明显增加内存，但是在另一个应用中，开多个客户端只有一个生效，
其他的还是会不断增大内存

**Comment by Joackk** [comment]
> 可以尝试限制一下最大缓存
> 
> ```dart
> void initVideo() async {
>     if (player.platform is NativePlayer) {
>       await (player.platform as dynamic).setProperty('cache', 'yes');
>     }
>     if (player.platform is NativePlayer) {
>       await (player.platform as dynamic).setProperty('demuxer-max-bytes', '30MiB');
>     }
>     if (player.platform is NativePlayer) {
>       await (player.platform as dynamic).setProperty('demuxer-readahead-secs', '20');
>     }
>   }
> ```
> 
> `demuxer-max-bytes ` 和 `demuxer-readahead-secs `
> 
> 我测试的时候没有明显增加内存，但是在另一个应用中，开多个客户端只有一个生效， 其他的还是会不断增大内存

这个问题似乎还不是固定的，因为我是偶尔会遇到，还不是此次都会遇到，就挺奇怪的

**Comment by MiaoMint** [comment]
可以试试 https://github.com/miru-project/miru-app/actions/runs/7256772092?pr=153

**Comment by Joackk** [comment]
> @Joackk 可以试试 https://github.com/miru-project/miru-app/actions/runs/7256772092?pr=153

感谢大佬

**Comment by MiaoMint** [comment]
还有这个问题嘛？ @Joackk

**Comment by Joackk** [comment]
> 还有这个问题嘛？ @Joackk

暂时的使用没有遇到，但是我不确定，因为之前他也不是固定触发，而是偶尔会触发，有时候蛮久都不触发。今天开了一天是没有遇到，应该没了

**Comment by romanticfire** [comment]
![image](https://github.com/miru-project/miru-app/assets/60844769/9c8a98fe-fbfd-464b-b39e-86131b41506c)
今天我使用也遇到了这个问题
大概连续看了四个小时左右
[miru.log](https://github.com/user-attachments/files/15518297/miru.log)
日志文件在这里
