### ISSUE TITLE
可以加入代理设置吗

### ISSUE THREAD

**Issue by Joackk** [miru-project/miru-app#139]
### Describe your suggested feature

在使用一些扩展时候，需要进行代理才能正常使用，但是软件本身似乎并没有设置代理的选项，暂时使用prox对程序进行代理来进行使用的，希望大佬可以给软件本身加一个设置代理的功能

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by MiaoMint** [comment]
#12
