### ISSUE TITLE
[Winodws] add horizontal scrollbar for Backdrops

### ISSUE THREAD

**Issue by bachig26** [miru-project/miru-app#185]
### Describe your suggested feature

for example, as show in the screenshot below, if the content has lot of images on their backdrops - miru can't able view all of them.

so, it would be best to have an scrollbar to navigate through them. also the current form, one couple images are shown and it cuts of everything from 3rd image if the title has more images as shown below.

screenshot:
![miru_4D6sjei18S](https://github.com/miru-project/miru-app/assets/96393348/f851a1e6-9731-4b5e-b0fe-540f75e08b4e)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by MiaoMint** [comment]
Holding down shift allows you to scroll with the mouse wheel.

**Comment by bachig26** [comment]
> Holding down shift allows you to scroll with the mouse wheel.

wooh...i didn't know this. thanks.

also if possible, can you add all available shortcut key functions in the documentation when you're updating it?
