### ISSUE TITLE
中文搜索结果的封面加载失败

### ISSUE THREAD

**Issue by Ftbom** [miru-project/miru-app#200]
### Brief summary

更新到1.8.0版本后，部分插件中使用中文搜索，搜索结果的封面无法加载，英文搜索结果没问题。
日志文件包含：`Bad state: Failed to load https://xxx.xxx/xxx.jpg.`，图片链接复制到浏览器是可以加载的
存在问题的插件举例：动漫之家、girigiri爱动漫
正常的插件举例：AGE动漫，MyIPTV
1.7.2版本没问题

### Miru version

1.8.0

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] If this is an issue with a extension, I should be opening an issue in the [extension repository](https://github.com/miru-project/repo/issues/new).

**Comment by MiaoMint** [comment]
girigiri爱动漫 修复了

**Comment by Ftbom** [comment]
感谢。
原来这是插件没有适配新版本，而不是程序自身的问题啊。那我关闭这个issue
