### ISSUE TITLE
Add unpacker

### ISSUE THREAD

**Issue by OshekharO** [miru-project/miru-app#211]
### Describe your suggested feature

It would be good to add [unpacker](https://www.npmjs.com/package/unpacker) for unpacking p.a.c.k.e.d strings. i.e. eval.

Also you can switch to this [crypto-js](https://www.npmjs.com/package/crypto-js) as it's being maintained, you can check whether default is better or this.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by MiaoMint** [comment]
Currently available libraries https://github.com/miru-project/miru-app/tree/dev/assets/js

**Comment by OshekharO** [comment]
> Currently available libraries https://github.com/miru-project/miru-app/tree/dev/assets/js

Yeah I know about them but I think they don't have function to decrypt packed strings i.e. eval. ( Probably? )
