### ISSUE TITLE
Version 1.7.0 plans

### ISSUE THREAD

**Issue by MiaoMint** [miru-project/miru-app#22]
- [x] CSS selectors
- [x] History record deletion feature
- [x] XPath selectors
- [x] Import button obscuring issue
- [x] #27
- [x] Image, video, and data requests with custom headers.
- [x] #35
- [x] #30
- [x] #40
- [x] #42
- [x]  #11 
- [x] #28

**Comment by OshekharO** [comment]
Need optimization for Android also i think search tab should be default and first and home should be renamed as favourite or history tab

**Comment by Fantuan-cell** [comment]
1.this.request方法新增httpParams和httpHeaders,分别对应参数键值对和请求头键值对.
 如下:const res = await this.request({
  url: "/xxx",
  method: "GET",
  httpParams:"请求的参数键值对",
  httpHeaders:"请求头键值对"
});

2.分类功能,可以参考我在tg群组发的图片借鉴下.使用键值对对应分类的请求.
3.搜索功能,可以增加一个搜索词联想功能,这个功能需要在源那里书源作者自己配置,如果没有配置就没有.
4.http2,请求是多一个参数判断是否使用http2功能,比如search,watch那里开启http2
5.增加读取压缩包里面的小说章节.某些特殊站点是传传压缩包结果,需要对压缩包处理.
6.http的参数可以选择是utf-8还是gbk编码

**Comment by MiaoMint** [comment]
> 1.this.request方法新增httpParams和httpHeaders,分别对应参数键值对和请求头键值对. 如下:const res = await this.request({ url: "/xxx", method: "GET", httpParams:"请求的参数键值对", httpHeaders:"请求头键值对" });
> 
> 2.分类功能,可以参考我在tg群组发的图片借鉴下.使用键值对对应分类的请求. 3.搜索功能,可以增加一个搜索词联想功能,这个功能需要在源那里书源作者自己配置,如果没有配置就没有. 4.http2,请求是多一个参数判断是否使用http2功能,比如search,watch那里开启http2 5.增加读取压缩包里面的小说章节.某些特殊站点是传传压缩包结果,需要对压缩包处理. 6.http的参数可以选择是utf-8还是gbk编码

header 和 method 是有的
