### ISSUE TITLE
Web Page crash when adding Anilist sync 

### ISSUE THREAD

**Issue by SkinoAsu** [miru-project/miru-app#227]
### Brief summary

After login my Anilist account  in miru the confirm page flash out and then the web page crashed so my account isn't add to the miru

NOTE: This is my case, might not able to repetition on other devices(I haven't try yet)

### Steps to reproduce

1.Open "Tracking" in settings
2.Select Anilist for sync povider
3.Click "Login"
4.Login my account
5.Web page crashed and my account isn't associated to miru

### Miru version

1.8.1

### Device

HUAWEI P40pro(HarmonyOS 4.0.0.128)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] If this is an issue with a extension, I should be opening an issue in the [extension repository](https://github.com/miru-project/repo/issues/new).

**Comment by MiaoMint** [comment]
#204 This has been fixed on the dev branch, and will be released later.
