### ISSUE TITLE
Android:允许列表内的快速定位条

### ISSUE THREAD

**Issue by mzltest** [miru-project/miru-app#23]
目前对于小说类等章节很多的列表没有提供滚动定位条，导致找特定的章节十分痛苦，希望添加。
![Screenshot_20230824_002143_miru miaomint](https://github.com/miru-project/miru-app/assets/52124882/db28b19c-344b-47c8-be2f-70bad08b44c9)
希望的效果（有滚动条就行，他这个是文件管理所以定位了）：
![Screenshot_20230824_002628_nextapp fx](https://github.com/miru-project/miru-app/assets/52124882/4fd2c432-dff9-47d6-86b0-be0fc98d6eb1)

另外顺便问下如何删除主页某个已经观看过的视频，我长按左右滑动都不行。

App 1.6.6

**Comment by MiaoMint** [comment]
是 F-Droid 啊那没事了 等待更新就好了，那个导入扩展确实是个问题 我已经给他添加到计划里了
