### ISSUE TITLE
how to creat extention ?

### ISSUE THREAD

**Issue by l3lb1** [miru-project/miru-app#250]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by appdevelpo** [comment]
https://github.com/appdevelpo/miru-extension-guide
It might not a good guide, but it may comes in handy. For more examples please check https://github.com/miru-project/repo
https://miru.js.org/en/developer/

**Comment by l3lb1** [comment]
@appdevelpo i thought it was easy but that hard for me cuz i dont know any programming language anyways thanks bro
