### ISSUE TITLE
 Anilist is not available!

### ISSUE THREAD

**Issue by RONUKUIGO** [miru-project/miru-app#252]
### Brief summary

After clicking login, there is no response and the page will return to the first page, resulting in failure to log in.

### Miru version

1.8.1

### Device

OPPO A58 5G

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] If this is an issue with a extension, I should be opening an issue in the [extension repository](https://github.com/miru-project/repo/issues/new).

**Comment by appdevelpo** [comment]
This issue had been solved but not release yet. You can check the [artifacts from action](https://github.com/miru-project/miru-app/actions/runs/8678090832)

**Comment by RONUKUIGO** [comment]
OK

在 2024年4月15日週一 11:59，appdevelpo ***@***.***> 寫道：
