### ISSUE TITLE
在登陆Anilist后无法追踪

### ISSUE THREAD

**Issue by sindeyzh** [miru-project/miru-app#253]
### Brief summary

我确认我的账户已经登录，并在网页端已经试过密码都是正确的

好像是在miru登录anilist后会有一个授权页面，但是瞬间就跳出了 继续显示需要登录，烦请问各位大佬们如何解决？

### Miru version

1.8

### Device

sony xperia 5 iii

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] If this is an issue with a extension, I should be opening an issue in the [extension repository](https://github.com/miru-project/repo/issues/new).

**Comment by MiaoMint** [comment]
#252

**Comment by sindeyzh** [comment]
OK,麻烦开发者大大了，谢谢
