### ISSUE TITLE
Add the ability to completely disable discord rich presence

### ISSUE THREAD

**Issue by BSoD38** [miru-project/miru-app#274]
### Describe your suggested feature

Hi, I've noticed that there is no way to completely disable Discord Rich Presence on Miru. I don't want to show this in my discord activity at all. The "Show details in discord rich presence" setting only disables which anime you are currently watching, but I just don't want to display anything at all. Miru isn't listed in the games list on Discord, do I don't think I can really disable it this way.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by appdevelpo** [comment]
It seems that you entered the wrong  [repo](https://github.com/ThaUnknown/miru) and started the issue. We didn't develop any discord related feature.

**Comment by BSoD38** [comment]
Woops! Very sorry, I have mixed up the repos indeed. I'm closing this issue.
