### ISSUE TITLE
why this?

### ISSUE THREAD

**Issue by ElainaTempest** [miru-project/miru-app#286]
### Brief summary

i want to watch anime in otakudesu,samehadaku but this
![Screenshot 2024-09-23 185729](https://github.com/user-attachments/assets/65b2fc45-62ed-44c5-a055-b0108a40b30f)

### Miru version

1.8.1

### Device

PC,Acer Aspire 3

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] If this is an issue with a extension, I should be opening an issue in the [extension repository](https://github.com/miru-project/repo/issues/new).

**Comment by iris1598** [comment]
看起来是插件问题，可以去这里提问https://github.com/miru-project/repo.
