### ISSUE TITLE
Excessive energy consumption

### ISSUE THREAD

**Issue by highglossypython** [miru-project/miru-app#298]
### Brief summary

The app(v 1.8.1) consumes excessive battery (MacOS Sequoia 15.0).
I had installed Miru from the public releases and for a few days I've noticed my macbook getting warm, which never happens. Today, it was extremely hot and I checked the activity monitor and found that Miru was consuming a lot of energy.
Even when a video is paused, when left open, Miru consumes a ton of battery. For comparison XCode is also running and debugging for longer than Miru while consuming a lot less energy.

### Steps to reproduce

1. Open Miru and activity monitor on mac
2. Open any anime episode
3. Pause the playback
4. Open any other app, leave Miru running in the background
5. Check back after a few hours on activity monitor
![Screenshot 2024-10-10 at 2 00 50 PM](https://github.com/user-attachments/assets/f948bde7-ff69-4398-b446-26f47058cc09)

### Miru version

1.8.1

### Device

Macbook Pro M3

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] If this is an issue with a extension, I should be opening an issue in the [extension repository](https://github.com/miru-project/repo/issues/new).

**Comment by appdevelpo** [comment]
It seems you open the issue at the wrong repository.
 [miru](https://github.com/ThaUnknown/miru)
