### ISSUE TITLE
我想请问直接git项目以后你们可以直接运行吗？

### ISSUE THREAD

**Issue by YuJunZhiXue** [miru-project/miru-app#314]
### Brief summary

我git项目以后，直接编译运行，总是报gradle错误，错误正在复现

### Steps to reproduce

* What went wrong:
A problem occurred evaluating project ':app'.
> Failed to apply plugin 'com.android.internal.version-check'.
   > Minimum supported Gradle version is 7.3.3. Current version is 7.2. If using the gradle wrapper, try editing the distributionUrl in D:\GithubPoject\KaiYuanXiangMu\miru-app\android\gradle\wrapper\gradle-wrapper.properties to gradle-7.3.3-all.zip

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org/ 

BUILD FAILED in 3m 24s
Error: Gradle task assembleDebug failed with exit code 1

### Miru version

“1.8.1”

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] If this is an issue with a extension, I should be opening an issue in the [extension repository](https://github.com/miru-project/repo/issues/new).

**Comment by YuJunZhiXue** [comment]
@appdevelpo 能解答一下吗

**Comment by OshekharO** [comment]
Minimum supported Gradle version is 7.3.3. Current version is 7.2 

Error is already mentioned in log 🪵

**Comment by YuJunZhiXue** [comment]
如果我修改build的话，不就和git冲突了吗

**Comment by YuJunZhiXue** [comment]
> 支持的最低 Gradle 版本为 7.3.3。当前版本为 7.2
> 
> 日志🪵中已提及错误

如果我修改build的话，不就和git冲突了吗

**Comment by appdevelpo** [comment]
你改了版本之後問題解決了？你擔心的git 衝突是...？如果是擔心build ci 那 build ci 就跟著一起改？ 最近我的flutter 版本更新後之前的專案很多都編不成功 = = ，想重新配置gradle java 還有 flutter版本，找時間試。

**Comment by OshekharO** [comment]
@YuJunZhiXue try invalidating cache

File > Invalidate Caches or Set up the Gradle Version in  Project Structure

**Comment by YuJunZhiXue** [comment]
> @YuJunZhiXue try invalidating cache
> 
> File > Invalidate Caches or Set up the Gradle Version in Project Structure

我使用的是IDEA
![image](https://github.com/user-attachments/assets/58a1f5fe-9083-4b89-bb91-9582345891a6)

**Comment by appdevelpo** [comment]
```
flutter clean 
flutter build apk
```
跟你確認一下flutter 的版本

**Comment by YuJunZhiXue** [comment]
> ```
> flutter clean 
> flutter build apk
> ```
> 
> 跟你確認一下flutter 的版本

flutter 3.19

**Comment by OshekharO** [comment]
> > @YuJunZhiXuetry invalidating cache
> > File > Invalidate Caches or Set up the Gradle Version in Project Structure
> 
> I am using IDEA ![image](https://private-user-images.githubusercontent.com/188421097/395040552-58a1f5fe-9083-4b89-bb91-9582345891a6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM5ODcyNjMsIm5iZiI6MTczMzk4Njk2MywicGF0aCI6Ii8xODg0MjEwOTcvMzk1MDQwNTUyLTU4YTFmNWZlLTkwODMtNGI4OS1iYjkxLTk1ODIzNDU4OTFhNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxMlQwNzAyNDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00YTBkZTJkYWI0NzhmNTQ2YjYwYzE2MDE4YTk1NTJkOGIwMWIwNjc1ODdhNjkzNDc2NDI2MDVkOTVlMjU3NmVkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Roymr_E2plZdSlaWUxsORmu2Q59kelDJ5MyL_cBpfOU)

Checkout project structure or invalidate cache there is option showing in the image you provided

**Comment by YuJunZhiXue** [comment]
> > > @YuJunZhiXuetry使缓存文件失效 >使缓存失效或在项目结构中设置 Gradle 版本
> > 
> > 
> > 我正在使用 IDEA![图像](https://private-user-images.githubusercontent.com/188421097/395040552-58a1f5fe-9083-4b89-bb91-9582345891a6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM5ODcyNjMsIm5iZiI6MTczMzk4Njk2MywicGF0aCI6Ii8xODg0MjEwOTcvMzk1MDQwNTUyLTU4YTFmNWZlLTkwODMtNGI4OS1iYjkxLTk1ODIzNDU4OTFhNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxMlQwNzAyNDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00YTBkZTJkYWI0NzhmNTQ2YjYwYzE2MDE4YTk1NTJkOGIwMWIwNjc1ODdhNjkzNDc2NDI2MDVkOTVlMjU3NmVkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Roymr_E2plZdSlaWUxsORmu2Q59kelDJ5MyL_cBpfOU)
> 
> 签出项目结构或使缓存失效，您提供的图像中显示选项

我使用此方法，现在报错如下
![image](https://github.com/user-attachments/assets/498e80d4-8aa3-456d-aa4a-26705918be03)

**Comment by YuJunZhiXue** [comment]
> > > > @YuJunZhiXuetry使缓存文件失效 >使缓存失效或在项目结构中设置 Gradle 版本
> > > 
> > > 
> > > 我正在使用 IDEA![图像](https://private-user-images.githubusercontent.com/188421097/395040552-58a1f5fe-9083-4b89-bb91-9582345891a6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM5ODcyNjMsIm5iZiI6MTczMzk4Njk2MywicGF0aCI6Ii8xODg0MjEwOTcvMzk1MDQwNTUyLTU4YTFmNWZlLTkwODMtNGI4OS1iYjkxLTk1ODIzNDU4OTFhNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxMlQwNzAyNDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00YTBkZTJkYWI0NzhmNTQ2YjYwYzE2MDE4YTk1NTJkOGIwMWIwNjc1ODdhNjkzNDc2NDI2MDVkOTVlMjU3NmVkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Roymr_E2plZdSlaWUxsORmu2Q59kelDJ5MyL_cBpfOU)
> > 
> > 
> > 签出项目结构或使缓存失效，您提供的图像中显示选项
> 
> 我使用此方法，现在报错如下 ![image](https://private-user-images.githubusercontent.com/188421097/395049429-498e80d4-8aa3-456d-aa4a-26705918be03.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM5ODk3NjEsIm5iZiI6MTczMzk4OTQ2MSwicGF0aCI6Ii8xODg0MjEwOTcvMzk1MDQ5NDI5LTQ5OGU4MGQ0LThhYTMtNDU2ZC1hYTRhLTI2NzA1OTE4YmUwMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxMlQwNzQ0MjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iNDYyMWQ0OGQ1OTU1ZjJiY2JmZDNhYjA5ZWJhMjhmMGZkMDlkZmY0MWVhZDA3NTI0ODAzYzY1MzU5YjEwMTNhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.KiWAPMxJ3YL182W0u5zcSe2H_HN4MGaqfq79JI3bIHI)

尝试修改，取消网络代理成功了，但是只是我的方法

**Comment by OshekharO** [comment]
> I use this method and now get the following error: ![image](https://private-user-images.githubusercontent.com/188421097/395049429-498e80d4-8aa3-456d-aa4a-26705918be03.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM5OTAzMzEsIm5iZiI6MTczMzk5MDAzMSwicGF0aCI6Ii8xODg0MjEwOTcvMzk1MDQ5NDI5LTQ5OGU4MGQ0LThhYTMtNDU2ZC1hYTRhLTI2NzA1OTE4YmUwMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxMlQwNzUzNTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03NzdiYWFiNmFmNTRjYmI3NGJhNzNhZmYwMWY0ZmNhMjhhMTlmZTg5ZDc5N2Y1Zjk4OTg5ZTBjYmM4OWI0NTRjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.62qVhE-ncJHY5nWGr0J0qqgOXl8raT_LQb_nvEE9gqo)

https://github.com/media-kit/media-kit/pull/656

Most probably Internet issue

**Comment by YuJunZhiXue** [comment]
> > I use this method and now get the following error: ![image](https://private-user-images.githubusercontent.com/188421097/395049429-498e80d4-8aa3-456d-aa4a-26705918be03.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM5OTAzMzEsIm5iZiI6MTczMzk5MDAzMSwicGF0aCI6Ii8xODg0MjEwOTcvMzk1MDQ5NDI5LTQ5OGU4MGQ0LThhYTMtNDU2ZC1hYTRhLTI2NzA1OTE4YmUwMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxMlQwNzUzNTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03NzdiYWFiNmFmNTRjYmI3NGJhNzNhZmYwMWY0ZmNhMjhhMTlmZTg5ZDc5N2Y1Zjk4OTg5ZTBjYmM4OWI0NTRjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.62qVhE-ncJHY5nWGr0J0qqgOXl8raT_LQb_nvEE9gqo)
> 
> [media-kit/media-kit#656](https://github.com/media-kit/media-kit/pull/656)
> 
> Most probably Internet issue

我按照修改成功下一步了，但是出现了找不到key的情况
这是为什么，我看代码写的是没有那个才会去寻找key

![image](https://github.com/user-attachments/assets/eb0d8602-0428-4004-92c0-b876ea383de2)

**Comment by appdevelpo** [comment]
要寫在環境參數或是放入指定位置來設定keystore 跟keypassword 

https://docs.flutter.dev/deployment/android

**Comment by YuJunZhiXue** [comment]
> 要寫在環境參數或是放入指定位置來設定keystore 跟keypassword
> 
> https://docs.flutter.dev/deployment/android

所以是需要我打包一次，编译成apk，自己生成key和keypasswd对吧

**Comment by appdevelpo** [comment]
是

**Comment by YuJunZhiXue** [comment]
> 是

那这个不需要上传到git仓库对吧

**Comment by appdevelpo** [comment]
不需要，如果檔案是在app目錄裡注意有沒有加進.gitnore

**Comment by YuJunZhiXue** [comment]
尝试运行成功了
