### ISSUE TITLE
English Language 

### ISSUE THREAD

**Issue by MrConqueror** [miru-project/miru-app#5]
Is there any way to change the app language, I'd like to change it to English is possible

**Comment by MiaoMint** [comment]
Hi, I noticed that you have requested English language support for our project. I'm glad to see your interest in the project! I have already mentioned in the project's README file that we have plans to internationalize (i18n) it to support multiple languages, including English, but it will take some time to implement.

**Comment by MiaoMint** [comment]
I have added i18n support in the latest version (1.2.0), and now it is possible to set English as the language of the software.
