### ISSUE TITLE
What is a "BT-SERVER"??

### ISSUE THREAD

**Issue by MarshMeadow** [miru-project/miru-app#50]
### Describe your suggested feature

I can install it, but I do not have the option to uninstall it..

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by MiaoMint** [comment]
Are you using the pc version?

**Comment by MiaoMint** [comment]
If you are using the PC version, you can find it in `Documents\miru` and delete it. I will add an uninstall option in a later version.

**Comment by OshekharO** [comment]
> What is it tho also??

Well it's used for streaming torrents within the miru application.

**Comment by HiroDane** [comment]
How to use it tho? I dont see any options for torrents in the desktop app except the BTserver option in settings
