### ISSUE TITLE
Add: Cloudflare killer and Opensubtitle integration

### ISSUE THREAD

**Issue by OshekharO** [miru-project/miru-app#52]
### Describe your suggested feature

Cloudflare killer: https://github.com/LagradOst/QuickNovel/blob/master/app/src/main/java/com/lagradost/quicknovel/network/CloudflareKiller.kt or cloudscraper: https://pypi.org/project/cloudscraper or https://pypi.org/project/bose/

How about adding ck, like you can also add webview implementation like kotatsu ( a managa reader ) to bypass cloudflare protection.

Also you can think about adding opensubtitle integration, like user's can search for subtitles within the application itself. For reference there's cloudstream application.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by MiaoMint** [comment]
This one seems a bit tricky.
