### ISSUE TITLE
Set webtoon mode as default 

### ISSUE THREAD

**Issue by OshekharO** [miru-project/miru-app#65]
### Describe your suggested feature

Instead of manually setting reading style of manga to webtoon can you please make it default or add an option to set which style the user want it to be default. Webtoon mode default for all manga source.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by MiaoMint** [comment]
After refactoring the settings I will add global settings options
