### ISSUE TITLE
BT play and extension repository

### ISSUE THREAD

**Issue by Pantyhose-X** [miru-project/miru-app#8]
You can refer to this torrent library

https://github.com/RangerMauve/bt-fetch and https://github.com/RangerMauve/bt-mut

https://github.com/webtorrent

Make a Torrent video source extension repository.  Get it from The Pirate Bay, etc. https://www.mizpee.com/best-torrent-sites/

**Comment by MiaoMint** [comment]
Thank you for your suggestion, but I'll probably use aria2

**Comment by aicynide** [comment]
@MiaoMint why aria2c? It'll download in disk space, use https://github.com/anacrolix/torrent for streaming torrent without downloading like https://github.com/YouROK/TorrServe

**Comment by MiaoMint** [comment]
@aicynide Wow! This looks good, I will use it.

**Comment by Pantyhose-X** [comment]
The bt-fetch and bt-mut I mentioned above also don't require the

**Comment by MiaoMint** [comment]
I'm sorry I didn't know much before, but both of these libraries are in JavaScript and it seems that not many people are using them.

**Comment by MiaoMint** [comment]
now supported

**Comment by Pantyhose-X** [comment]
> I'm sorry I didn't know much before, but both of these libraries are in JavaScript and it seems that not many people are using them.

It's integrated into its [Agregore Browser](https://github.com/AgregoreWeb/agregore-browser). You can try it.
But it loads so fast, you don't even have to wait to watch the video.

Add a torrent search source [torrents-csv](https://torrents-csv.ml/)
